install.packages('dplyr')
install.packages('ggplot2')
install.packages('fitzRoy')
install.packages('tibble')
install.packages('tidyr')
library(dplyr)
library(ggplot2)
library(fitzRoy)
library(tibble)
library(tidyr)

# Tadhg Xu-Glassop

# displays all information
help <- function() {
    cat("Data can be generated by using get_stats(years), where years is a vector\n")
    cat("For example, type: \n")
    cat("   results <- get_stats(c(2023, 2024))\n")
    cat("To get results and statistics from all matches between 2023 and 2024\n\n")
    cat("Data about a specific player can be interpreted using get_player_stats(results)\n")
    cat("For example, type:\n")
    cat("   moments <- get_player_stats(results)\n")
    cat("To get the moments of any statistic regarding a player.\n\n")
    cat("To calculate upper tail probabilities, use calc_pr(moments)\n")
    cat("For example, type:\n")
    cat("   calc_pr(moments)\n")
    cat("And you will be prompted for specific statistics and measurements.\n")
    cat("The above can be combined into one function call with full_calc_pr, for example,\n")
    cat("   full_calc_pr(results)\n")
}

# Load player stats - years are the argument
get_stats <- function(years = c(2023, 2024)) {
    player_stats <- fetch_player_stats(season = years, source = "fryzigg")
    return(player_stats)
}


# Takes 1 player name, and returns any wanted statistics
get_player_stats <- function(player_stats) {
    # loop that retrives a player's stats
    first_name <- readline(prompt = "Enter first name: ")
    last_name <- readline(prompt = "Enter last name: ")
    selected_stats <- c("date", "player_last_name")

    repeat {
        stat_name <- readline(prompt = "Enter statistic ('help' for cmds, 'done' to exit): ")

        if (tolower(stat_name) == "help") {
            print(names(player_stats))
        } else if (tolower(stat_name) == "done") {
            break
        } else if (stat_name %in% names(player_stats)) {
            cat("Adding ", stat_name, "...\n")
            selected_stats <- c(selected_stats, stat_name)
        } else {
            cat("Stat not found, try again\n")
        }
    }

    # filter for first and last name
    given_player_stats <- player_stats %>% 
        filter(player_last_name == last_name) %>%
        filter(player_first_name == first_name) %>%
        select(all_of(selected_stats))

    # error checking
    if (nrow(given_player_stats) == 0) {
        cat("No stats found for ", last_name, "\n")
        return(given_player_stats)
    }

    # Get expectation and variance of stats
    averages <- colMeans(given_player_stats[ , -c(1,2)])
    exp_player_stats <- data.frame(statistic = names(averages), average = averages)

    var_player_stats <- given_player_stats %>%
        select(-c(1,2)) %>%
        summarise(across(everything(), var)) %>%
        pivot_longer(everything(),  names_to = "statistic", values_to = "variance")

    combined_stats <- exp_player_stats %>%
        left_join(var_player_stats, by = "statistic")

    combined_stats <- as.data.frame(combined_stats)

    return(combined_stats)
}

# Take 1 statistic, and get player names, returning the statistic of interest for all players
get_stat_for_players <- function(player_stats) {
    # get 1 statistic of interest
    repeat {
        stat_name <- readline(prompt = "Enter statistic of interest ('help' for all options): ")
        if (tolower(stat_name) == "help") {
            print(names(player_stats))
        } else if (stat_name %in% names(player_stats)) {
            break
        } else {
            cat("Error finding stat. Try again\n")
        }

    }

    final_stats <- tibble(
        name = character(),
        statistic = character(),
        average = double(),
        variance = double()
    )

    repeat {
        first_name <- readline(prompt = "Enter first name (or 'done' to exit): ")

        if (tolower(first_name) == "done") {
            break
        }

        last_name <- readline(prompt = "Enter last name: ")
        
        if (!(any(player_stats$player_first_name == first_name) && any(player_stats$player_last_name == last_name))) {
            cat("Could not find player", first_name, last_name, "\n")
            next
        }


        # get stats for this player, then find mean and average and add it to our final result
        selected_stats <- c("date", "player_last_name", stat_name)

        # filter for first and last name
        given_player_stats <- player_stats %>% 
            filter(player_last_name == last_name) %>%
            filter(player_first_name == first_name) %>%
            select(all_of(selected_stats))

        # Get expectation and variance of stats
        averages <- colMeans(given_player_stats[ , -c(1,2)])
        exp_player_stats <- data.frame(name = last_name, statistic = names(averages), average = averages)

        var_player_stats <- given_player_stats %>%
            select(-c(1,2)) %>%
            summarise(across(everything(), var)) %>%
            pivot_longer(everything(),  names_to = "statistic", values_to = "variance")

        combined_stats <- exp_player_stats %>%
            left_join(var_player_stats, by = "statistic")

        final_stats <- bind_rows(final_stats, combined_stats)
    }
    return(as.data.frame(final_stats))
}


visualise <- function(player_stats) {
    # get data to be plotted
    first_name <- readline(prompt = "Enter first name: ")
    last_name <- readline(prompt = "Enter last name: ")
    selected_stats <- c("date", "player_last_name")

    repeat {
        stat_name <- readline(prompt = "Enter statistic ('help' for cmds): ")

        if (tolower(stat_name) == "help") {
            print(names(player_stats))
        } else if (stat_name %in% names(player_stats)) {
            selected_stats <- c(selected_stats, stat_name)
            break
        } else {
            cat("Stat not found, try again\n")
        }
    }

    # filter for last name
    given_player_stats <- player_stats %>% 
        filter(player_last_name == last_name) %>%
        filter(player_first_name == first_name) %>%
        select(all_of(selected_stats))

    ggplot(given_player_stats, aes_string(x = stat_name)) +
        geom_bar() +
        labs(title = "Bar Plot") +
        theme_minimal()
    
}


# Take a t distribution for probability calculation, with classic definition
calc_pr_t <- function(moments) {
    if (length(moments) == 0) {
        cat("\n>> Data entry unsuccessful<<")
        stop()
    }
    cat("\n>> Data entry successful and using t distribution <<\n\n")
    print(moments)
    cat("\n")

    repeat {
        stat <- readline(prompt = "Enter statistic to be exceeded ('done' to exit): ")
        if (tolower(stat) == "done") {
            break
        } else if (stat %in% moments$statistic) {
            num <- readline(prompt = "Enter minimum value: ")
            num <- as.integer(num)
            mean <- moments[which(moments$statistic == stat), "average"]
            var <- moments[which(moments$statistic == stat), "variance"] / length(moments)
            t <- (num - mean) / sqrt(var)
            prob <- pt(t, length(moments), lower.tail = FALSE)
            fair_odds <- prob^-1

            cat("Probability of", stat, "exceeding", num, "is", prob, "// Fair odds are", fair_odds, "\n")

        } else {
            cat("Couldn't find statistic\n")
        }
    }
}

# Assume a normal model for our means. find probability it exceeds a given number
calc_pr_n <- function(moments) {
    if (length(moments) == 0) {
        cat("\n>> Data entry unsuccessful<<")
        stop()
    }

    cat("\n>> Data entry successful and using normal distribution <<\n")
    print(moments)
    cat("\n")

    repeat {
        stat <- readline(prompt = "Enter statistic/last name of interest ('done' to exit): ")
        if (tolower(stat) == "done") {
            break
        } else if (stat %in% moments$statistic || stat %in% moments$name) {
            num <- readline(prompt = "Enter minimum value: ")
            num <- as.integer(num)
            prob <- pnorm(num, mean = moments[which(moments[[1]] == stat), "average"], 
                    sd = sqrt(moments[which(moments[[1]] == stat), "variance"]), 
                    lower.tail = FALSE)
            fair_odds <- prob^-1
            cat("Probability of", stat, "exceeding", num, "is", prob, "// Fair odds are", fair_odds, "\n")
        } else {
            cat("Couldn't find statistic\n")
        }
    }
}

# Runs through whole probability calculation for a player
full_calc_pr <- function(results) {
    cat("For multiple statistics of a single player, enter '1'\n")
    cat("For multiple players results of a single statistic, enter '2'\n")
    option <- readline(prompt = "Enter command: ")
    if (option == '1') {
        moments <- get_player_stats(results)
    } else if (option == '2') {
        moments <- get_stat_for_players(results)
    } else {
        cat("Error, didn't recognise command", option, "Exiting...\n")
        stop()
    }

    repeat {
        dist <- readline(prompt = "For probability calculation, enter t for t distribution, or n for normal distribution: ")
        if (dist == 't') {
            calc_pr_t(moments)
            break
        } else if (dist == 'n') {
            calc_pr_n(moments)
            break
        } else {
            cat("Error: did not recognise distribution. Please try again\n")
        }
    }
}



